#Para definir qual a versão do python utilizada no projeto
FROM python:3.12

ENTRYPOINT [ "tail", "-f", "/dev/null" ]

#Para definir o Diretório do trabalho no container
# WORKDIR /app

#Para copiar todos os arquivos python para o contêiner
# COPY . src/app

