version: '3'
services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ElS895623!
      MYSQL_DATABASE: marketplace_veiculos

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  app:
    build: .
    volumes:
      - "./aula:/src"
    ports:
      - "8001:8000"  
      - "4000:4000"

volumes:
  dbbase:
