# Generated by Django 5.1.4 on 2024-12-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
    ]
